image:
  lfaiRagTag: "0.2.0"

rag:
  replicas: "1"

env:
  openaiApiBase: "###ZARF_VAR_API_BASE###"
  openaiApiKey: "###ZARF_CONST_API_KEY###"
  model: "###ZARF_VAR_MODEL###"
  temperature: "###ZARF_VAR_TEMPERATURE###"
  contextWindow: "###ZARF_VAR_CONTEXT_WINDOW###"
  maxOutput: "###ZARF_VAR_MAX_OUTPUT###"
  chunkSize: "###ZARF_VAR_CHUNK_SIZE###"
  overlapSize: "###ZARF_VAR_OVERLAP_SIZE###"
  responseMode: "###ZARF_VAR_RESPONSE_MODE###"
  sslVerification: "###ZARF_VAR_SSL_VERIFICATION###"
  prefix: "###ZARF_VAR_PREFIX###"
  embeddingModelName: "###ZARF_VAR_EMBEDDING_MODEL_NAME"